name: MacOS Build Status 

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup dotfiles
        run: ./bin/macos-install.sh
